#version 430

layout(local_size_x = 16, local_size_y = 16) in;

layout(r16ui, binding = 0) uniform writeonly uimage2D materialTex;
layout(r16f, binding = 3) uniform writeonly image2D waterAmountTex;
layout(rg16f, binding = 4) uniform writeonly image2D waterVelocityTex;

uniform ivec2 gridSize;

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    if (coord.x >= gridSize.x || coord.y >= gridSize.y) {
        return;
    }

    imageStore(materialTex, coord, uvec4(0u));
    imageStore(waterAmountTex, coord, vec4(0.0));
    imageStore(waterVelocityTex, coord, vec4(0.0));
}
